language: ruby
rvm:
  - 2.2.4
env:
  - DB=postgresql
script:
  - bundle exec rake spec
before_script:
  - rails db:create
  - rails db:migrate
  - rails db:test:prepare
bundler_args: --binstubs=./bundler_stubs